### ISSUE TITLE
Edit Window Extends Beyond Screen Boundaries

### ISSUE THREAD

**Issue by hadijannat** [rwth-iat/aas_manager#22]
### What happened?

**Description:**

When accessing the AAS manager (version 0.3.7), there is a recurrent issue where the edit window extends beyond the upper boundary of the monitor, obscuring the action button. This requires the user to drag the window upwards to reveal the button, which is only sometimes convenient or immediately apparent, leading to a suboptimal user experience.

**Steps to Reproduce:**

1. Open the AAS manager.
2. Navigate to any submodel, such as 'TechnicalData'.
3. Click to edit or create an object.
4. Observe that the edit window opens, so the action button is off-screen.

**Expected Behavior:**
The action button should be easily accessible without needing to adjust the position of the edit window.

**Actual Behavior:**
The action button is hidden above the top edge of the monitor, requiring the user to drag the window to view and interact with it.

**Possible Fixes:**
An initial suggestion for a fix would be to ensure that the edit window's default position is centered within the screen's visible area or that it dynamically adjusts based on the screen resolution.

Screenshots
![Screenshot 2024-02-21 094907](https://github.com/rwth-iat/aas_manager/assets/111177329/5d6a5890-d6fe-4bde-aa42-86106ceb61cc)

**Environment**:

- AAS Manager Version: 0.3.7
- Operating System: (Your Operating System and version)
- Screen Resolution: (Your Screen Resolution)

**Additional Context:**
This issue has been a minor inconvenience, and while it doesn't prevent the use of the application, it does affect workflow efficiency.

**Comment by zrgt** [comment]
This bug should be solved by saving the last position of dialog. A new issue is opened for this purpose (#28)
